// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCrnrCInQvSZ0AVy31UOXDZXLSGFkU6M4',
    appId: '1:772037827019:web:6be6871bed17d14b423e4e',
    messagingSenderId: '772037827019',
    projectId: 'fir-8-e7ecb',
    authDomain: 'fir-8-e7ecb.firebaseapp.com',
    storageBucket: 'fir-8-e7ecb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-tANbJSs4c4IIZIEdriOICIixPfHgONg',
    appId: '1:772037827019:android:105efd6cae3eb6d5423e4e',
    messagingSenderId: '772037827019',
    projectId: 'fir-8-e7ecb',
    storageBucket: 'fir-8-e7ecb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ROxYDbIx7-KDQXFDNBqRhoX-CDUr7fc',
    appId: '1:772037827019:ios:b309fd8edb299774423e4e',
    messagingSenderId: '772037827019',
    projectId: 'fir-8-e7ecb',
    storageBucket: 'fir-8-e7ecb.firebasestorage.app',
    iosBundleId: 'com.example.atividade8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ROxYDbIx7-KDQXFDNBqRhoX-CDUr7fc',
    appId: '1:772037827019:ios:b309fd8edb299774423e4e',
    messagingSenderId: '772037827019',
    projectId: 'fir-8-e7ecb',
    storageBucket: 'fir-8-e7ecb.firebasestorage.app',
    iosBundleId: 'com.example.atividade8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCrnrCInQvSZ0AVy31UOXDZXLSGFkU6M4',
    appId: '1:772037827019:web:25560ff7c9a25d73423e4e',
    messagingSenderId: '772037827019',
    projectId: 'fir-8-e7ecb',
    authDomain: 'fir-8-e7ecb.firebaseapp.com',
    storageBucket: 'fir-8-e7ecb.firebasestorage.app',
  );
}
